BlueDiamond/Models/IncidentViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using AutoMapper;
using BlueDiamond.DataModel;
using BlueDiamond.Utility;

namespace BlueDiamond.Models
{
    public class IncidentViewModel
    {
        public IncidentViewModel() { }

        static IncidentViewModel()
        {
            Mapper.CreateMap<Incident, IncidentViewModel>();
            Mapper.CreateMap<IncidentViewModel, Incident>();
        }

        public static IncidentViewModel Create(Incident incident)
        {
            var i = Mapper.Map<IncidentViewModel>(incident);
            i.Opened = incident.Opened.ToLocal(incident.Agency.TimeZone);
            i.Closed = incident.Closed.ToLocal(incident.Agency.TimeZone);
            return i;
        }

        public Incident ToIncident()
        {
            return Mapper.Map<Incident>(this);
        }
        public Guid IncidentID { get; set; }
        public Guid AgencyID{ get; set; }

        public Agency Agency { get; set; }

        public Core Core { get; set; }

        #region properties

        [Display(Name = "Task #")]
        [Required(ErrorMessage = "Task Number is required")]
        public int TaskNumber { get; set; }

        public string Data { get; set; }

        [Display(Name = "RCMP #")]
        public string RCMPNumber { get; set; }

        [Display(Name = "BCAS #")]
        public string BCASNumber { get; set; }

        [Display(Name = "ASE #")]
        public string ASENumber { get; set; }

        [Display(Name = "Sign In Location")]
        public string Location { get; set; }

        [Display(Name = "Incident Description")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Incident Name is required")]
        [Display(Name = "Incident Name")]
        public string Name { get; set; }

        [Display(Name = "Started")]
        public DateTime Opened { get; set; }

        [Display(Name = "Finished")]
        public DateTime? Closed { get; set; }

        #endregion

        public bool IsOpen { get { return this.Closed == null; } }
    }
}

BlueDiamond/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using BlueDiamond.DataModel;
using BlueDiamond.Models;
using BlueDiamond.StorageModel;
using System.Data.Entity;

namespace BlueDiamond.Controllers
{
    public class EventsController : BaseController
    {
        ApplicationDbContext m_db = new ApplicationDbContext();

        public UserManager<ApplicationUser> m_userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));

        public ActionResult View(Guid? id)
        {
            //if (!User.Identity.IsAuthenticated)
            //    return RedirectToAction("Login", "Account");

            //ApplicationUser user = m_userManager.FindById(User.Identity.GetUserId());
            //if (user== null || user.Agent.Agency == null)
            //    return RedirectToAction("LoggedIn", "Home");

            Incident incident = GetIncident(id, null);
            IncidentEventsViewModel model = new IncidentEventsViewModel()
            {
                Incident = incident,
                //Agency = user.Agent.Agency,
                //Agent = user.Agent
            };

            return View(model);
        }

        public ActionResult RadioLog(Guid? id)
        {
            if(!id.HasValue)
                return RedirectToAction("Error");
            var incident =  m_db.Incidents.Include(x=>x.Events).Include("Events.Attachments").FirstOrDefault(x=>x.IncidentID==id);

            List<MessageData> log = incident
                .Events
                .Where(x => x.Data == TagTypes.LOG)
                .OrderByDescending(x=>x.Core.Created)
                .Select<Event, MessageData>(x => x.Attachments.OfType<MessageData>().FirstOrDefault())
                .ToList();
            
            ViewBag.IncidentID = id;
            
            RadioLogViewModel model = new RadioLogViewModel()
            {
                Incident = incident,
                Log = log,
                NewLog = new MessageData() { Data=id.ToString()}

            };
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> RadioLog(Guid id,[Bind(Include = "From,To,Message,Data,Core")]MessageData messageData)
        {
            //Guid id = new Guid(messageData.Data);
            messageData.AttachmentID = Guid.NewGuid();
            Event e = new Event()
            {
                IncidentID = id,
                Data = TagTypes.LOG,
                Core = Core.Create(User.Identity.Name)
            }.AddAttachment(messageData);

            if (ModelState.IsValid)
            {
                //agencyModel.AgencyID = Guid.NewGuid();
                m_db.Events.Add(e);
                await m_db.SaveChangesAsync();
            }

            return RedirectToAction("RadioLog", new { id = id });
        }

       

        /// <summary>
        /// If the incident ID is null, 
        /// * return the incident the user is logged into 
        /// * return the default incident
        /// otherwise return the incident that has the given ID
        /// </summary>
        /// <param name="incidentID"></param>
        /// <param name="user"></param>
        /// <returns></returns>
        private Incident GetIncident(Guid? incidentID,ApplicationUser user)
        {
            // find the User
            if (!incidentID.HasValue)
            {
                if (user == null)
                    return m_db.Incidents.Find(Incident.ROOT_INCIDENT);

                // figure out what Incident the user is signed in to
                var si = m_db.SignIns.Where(x => x.MemberID == user.Agent.MemberID && !x.SignedOut.HasValue).FirstOrDefault();
                return
                (si == null) ?
                    m_db.Incidents.Find(Incident.ROOT_INCIDENT) :
                    si.Incident;
            }
            else
            {
                return m_db.Incidents.Find(incidentID);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (m_userManager != null)
                    m_userManager.Dispose();
                m_userManager = null;

                if (m_db != null)
                    m_db.Dispose();
                m_db = null;
            }
            base.Dispose(disposing);
        }

    }
}

BlueDiamond/Controllers/IncidentsController.cs
using System;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using BlueDiamond.DataModel;
using BlueDiamond.Models;
using BlueDiamond.StorageModel;
using BlueDiamond.Utility;
using Gma.QrCodeNet.Encoding;
using Gma.QrCodeNet.Encoding.Windows.Controls;

namespace BlueDiamond.Controllers
{
    public class IncidentsController : BaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public async Task<ActionResult> Index()
        {
            var incidents = await db
                .Incidents
                .Where(x => !x.Core.IsDeleted)
                .Include(i => i.Agency)
                .OrderByDescending(x => x.Opened)
                .ToListAsync();
            return View(incidents);
        }

        public string GetUrl()
        {
            return string.Format("http://{0}:{1}/", GetIPAddress(), Request.Url.Port);
        }

        public FileContentResult Show(Guid id)
        {
            QrEncoder enc = new QrEncoder();
            QrCode code = enc.Encode(GetUrl());

            Renderer renderer = new Renderer(5);
            Image image = new Bitmap(256,256);
            using (Graphics graphics = Graphics.FromImage(image))
                renderer.Draw(graphics, code.Matrix);

            byte[] imageByte = imageToByteArray(image);
            string contentType = "image/png";

            return File(imageByte, contentType);
        }

        public byte[] imageToByteArray(Image imageIn)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                imageIn.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                return ms.ToArray();
            }
        }
        public string GetIPAddress()
        {
            string myHost = System.Net.Dns.GetHostName();
            string ipAddress = System.Net.Dns.GetHostEntry(myHost).AddressList.FirstOrDefault(x=>x.AddressFamily== System.Net.Sockets.AddressFamily.InterNetwork).ToString();
            return ipAddress;
        }

        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Incident incident = await db.Incidents.FindAsync(id);
            if (incident == null)
                return HttpNotFound();
            return View(incident);
        }

        public ActionResult Create()
        {
            ViewBag.AgencyID = new SelectList(db.Agencies, "AgencyID", "Name");
            return View();
        }

        // POST: Incidents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "IncidentID,Core,TaskNumber,RCMPNumber,BCASNumber,ASENumber,Location,Description,Name,Opened,Closed,AgencyID,Agency")] IncidentViewModel incidentModel)
        {
            Incident incident = incidentModel.ToIncident();
            if (ModelState.IsValid)
            {
                incident.Agency = await db.Agencies.FindAsync(incident.AgencyID);
                incident.Opened = DateTime.UtcNow;
                incident.IncidentID = Guid.NewGuid();
                incident.Core = Core.Create(User.Identity.Name);
                db.Incidents.Add(incident);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.AgencyID = new SelectList(db.Agencies, "AgencyID", "Name", incident.AgencyID);
            return View(incident);
        }

        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Incident incident = await db.Incidents.Include(x => x.Agency).FirstOrDefaultAsync(x => x.IncidentID == id);
            if (incident == null)
                return HttpNotFound();
            ViewBag.AgencyID = new SelectList(db.Agencies, "AgencyID", "Name", incident.AgencyID);
            return View(IncidentViewModel.Create(incident));
        }

        // POST: Incidents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "IncidentID,Core,TaskNumber,RCMPNumber,BCASNumber,ASENumber,Location,Description,Name,Opened,Closed,AgencyID")] IncidentViewModel incidentModel)
        {
            
            Incident incident = incidentModel.ToIncident();
            if (ModelState.IsValid)
            {
                incident.Agency = await db.Agencies.FindAsync(incident.AgencyID);
                incident.Opened = incidentModel.Opened.ToUtc(incident.Agency.TimeZone);
                incident.Closed = incidentModel.Closed.ToUtc(incident.Agency.TimeZone);

                incident.Core.Modify(User.Identity.Name);
                db.Entry(incident).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.AgencyID = new SelectList(db.Agencies, "AgencyID", "Name", incident.AgencyID);
            return View(IncidentViewModel.Create(incident));
        }

        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Incident incident = await db.Incidents.FindAsync(id);
            if (incident == null)
                return HttpNotFound();
            return View(incident);
        }

        // POST: Incidents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            Incident incident = await db.Incidents.FindAsync(id);
            incident.Core.Delete(User.Identity.Name);
            //db.Incidents.Remove(incident);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Do sign-in form for incident with the given ID
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> SignIn(Guid id, Guid? memberID)
        {
            if (memberID.HasValue)
            {
                SignIn si = new SignIn()
                {
                    IncidentID = id,
                    MemberID = memberID.Value
                };

                db.SignIns.Add(si);
                Member member = await db.Members.FindAsync(memberID);
                Helpers.SignalSignIn(id, member.LastName, member.FirstName, si.SignedIn);
                await db.SaveChangesAsync();
            }

            CheckInViewModel model = new CheckInViewModel();
            model.Incident = db.Incidents.Include(i => i.SignIns).FirstOrDefault(x => x.IncidentID == id);

            var signIns = db.SignIns
                .Where(x => x.IncidentID == id)
                .ToList();

            model.SignIns = db.Members.Select<Member, MemberSignIn>(x => new MemberSignIn() { Member = x }).ToList();

            foreach (var m in model.SignIns)
            {
                var si = signIns
                    .OrderByDescending(x => x.SignedIn)
                    .FirstOrDefault(x => x.MemberID == m.Member.MemberID);
                if (si != null)
                    m.SignIn = si;
            }
            return View(model);
        }

        public async Task<ActionResult> SignOut(Guid id, Guid memberID)
        {
            //retrieve the sign in record
            var incident = db
                .Incidents
                .Include(i => i.SignIns)
                .FirstOrDefault(x => x.IncidentID == id);

            var si = incident
                .SignIns
                .Where(x=>!x.SignedOut.HasValue)
                .FirstOrDefault(x => x.MemberID == memberID);
            
            if(si==null)
            {
                // return an error that the si was not found
            }

            si.SignedOut = DateTime.UtcNow;
            await db.SaveChangesAsync();
            
            return RedirectToAction("SignIn", new { id = id });
        }

        public async Task<ActionResult> Open(Guid id)
        {
            var incident = await db.Incidents.FindAsync(id);
            incident.Open();
            await db.SaveChangesAsync();
            return RedirectToAction("Details", new { id = id });
        }

        public async Task<ActionResult> Close(Guid id)
        {
            var incident = await db.Incidents.FindAsync(id);
            incident.Close();
            await db.SaveChangesAsync();
            return RedirectToAction("Details", new { id = id });
        }

        public async Task<ActionResult> SignInStatus(Guid id)
        {
            CheckInViewModel model = new CheckInViewModel();
            model.Incident = await db.Incidents.FindAsync(id);
            model.SignIns = await db
                .SignIns
                .Where(x => x.IncidentID == id)
                .Where(x => x.SignedOut == null)
                .Join(db.Members,
                    s => s.MemberID,
                    m => m.MemberID,
                    (s, m) => new MemberSignIn() { Member = m, SignIn = s })

BlueDiamond/Views/Incidents/Create.cshtml
@model BlueDiamond.Models.IncidentViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<div class="row">
    <div class="col-md-6">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Incident</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.TaskNumber, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.TaskNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TaskNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RCMPNumber, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.RCMPNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RCMPNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BCASNumber, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.BCASNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BCASNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ASENumber, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.ASENumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ASENumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AgencyID, "AgencyId", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownList("AgencyId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.AgencyID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-md-3"></div>
    <div class="col-md-3"></div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BlueDiamond/Views/Incidents/Delete.cshtml
@model BlueDiamond.DataModel.Incident

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>

<div>
    @Html.Partial("_Incident", Model)

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BlueDiamond/Views/Incidents/Details.cshtml
@model BlueDiamond.DataModel.Incident

@{
    ViewBag.Title = "Incident";
}


        @Html.Partial("_Incident", Model)
 

<hr />
<div class="row">
    <div class="col-md-2">
        @if (Model.IsOpen)
        {
            @Html.ActionLink("Close", "Close", "Incidents", new { id = Model.IncidentID }, new { @class = "btn btn-primary" })
        }
        else
        {
            @Html.ActionLink("Open", "Open", "Incidents", new { id = Model.IncidentID }, new { @class = "btn btn-success" })
        }
    </div>
    <div class="col-md-2">
        <p>@Html.ActionLink("Sign In", "SignIn", "Incidents", new { id = Model.IncidentID }, new { @class = "btn btn-default" }) </p>
    </div>
    <div class="col-md-2">
        <p>@Html.ActionLink("Radio Log", "RadioLog", "Events", new { id = Model.IncidentID }, new { @class = "btn btn-default" }) </p>
    </div>
    <div class="col-md-2">
        <p>@Html.ActionLink("Sign In Status", "SignInStatus", "Incidents", new { id = Model.IncidentID }, new { @class = "btn btn-default" }) </p>
    </div>
    <div class="col-md-2">
        <p>@Html.ActionLink("Edit", "Edit", new { id = Model.IncidentID }, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-2">
        <p>@Html.ActionLink("Tracks", "Index", "Tracks", new { id = Model.IncidentID }, new { @class = "btn btn-default" })</p>
    </div>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

BlueDiamond/Views/Incidents/Index.cshtml
@model IEnumerable<BlueDiamond.DataModel.Incident>

@{
    ViewBag.Title = "Incident";
}

<h2>Incidents</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th> @Html.DisplayNameFor(model => model.TaskNumber) </th>
        <th> @Html.DisplayNameFor(model => model.Name) </th>
        <th> @Html.DisplayNameFor(model => model.Opened) </th>
        <th> @Html.DisplayNameFor(model => model.Closed) </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td> @Html.DisplayFor(modelItem => item.TaskNumber) </td>
        <td> @Html.DisplayFor(modelItem => item.Name) </td>
        <td> @Html.DisplayFor(modelItem => item.Opened) </td>
        <td> @Html.DisplayFor(modelItem => item.Closed) </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IncidentID }) |
            @Html.ActionLink("Details", "Details", new { id=item.IncidentID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.IncidentID }) |
            @Html.ActionLink("Sign In", "SignIn", new { id = item.IncidentID })
        </td>
    </tr>
}

</table>

BlueDiamond/Views/Incidents/SignIn.cshtml
@model BlueDiamond.Models.CheckInViewModel

@{
    ViewBag.Title = "SignIn";
}

@Html.Partial("_Incident", Model.Incident)


<h2>Sign in to task  </h2>
<hr/>
<table class="table">
    <tr>
        <th> Last Name </th>
        <th> First Name </th>
        <th> Signed In</th>
        <th> Signed Out</th>
        <th></th>
    </tr>

    @foreach (var item in Model.SignIns) {
        <tr>
            <td> @Html.DisplayFor(modelItem => item.Member.LastName) </td>
            <td> @Html.DisplayFor(modelItem => item.Member.FirstName) </td>
            <td> @Html.DisplayFor(modelItem => item.SignInTime) </td>
            <td> @Html.DisplayFor(modelItem => item.SignOutTime) </td>
            <td> @if (item.IsSignedIn)
            {
                @Html.ActionLink("Sign Out", "SignOut", "Incidents", new { id = Model.Incident.IncidentID, memberID = item.MemberID }, new { @class = "btn btn-success" });
            }
            else
            {
                @Html.ActionLink("Sign In", "SignIn", "Incidents", new { id = Model.Incident.IncidentID, memberID = item.MemberID }, new { @class = "btn btn-default" });
            }
            </td>
            <td> </td>
        </tr>
    }
</table>

BlueDiamond/Views/Incidents/SignInStatus.cshtml
@model BlueDiamond.Models.CheckInViewModel

@{
    ViewBag.Title = "SignIn Status";
}

<h2>SignIn Status for Incident @Html.DisplayFor(model=>model.Incident.TaskNumber)</h2>

<table class="table">
    <thead>
        <tr>
            <th> Last Name</th>
            <th> First Name </th>
            <th> Sign In Time </th>
        </tr>
        </thead>
    <tbody id="update">
        @foreach (var item in Model.SignIns)
        {
            <tr>
                <td> @Html.DisplayFor(modelItem => item.Member.LastName) </td>
                <td> @Html.DisplayFor(modelItem => item.Member.FirstName) </td>
                <td> @Html.DisplayFor(modelItem => item.SignInTime) </td>
            </tr>
        }
    </tbody>
</table>
@section scripts {
<script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
<script src="~/signalr/hubs"></script>
<script type="text/javascript">
    $(function () {
        var events = $.connection.eventHub;
        events.client.login = function (lastname, firstname, signintime) {
            $('#update').prepend("<tr><td>" + lastname + "</td><td>" + firstname + "</td><td>" + signintime + "</td></tr>");
        };

        $.connection.hub.start().done(function () {
            events.server.joinIncident("@Model.Incident.IncidentID.ToString()");
        });

    });
</script>
}

BlueDiamond/Views/Incidents/_Incident.cshtml
@model BlueDiamond.DataModel.Incident

<div>
    <h1>Incident @Html.DisplayFor(model => model.TaskNumber)</h1>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <dl class="dl-horizontal">
                <dt> @Html.DisplayNameFor(model => model.Name): </dt>
                <dd> @Html.DisplayFor(model => model.Name) </dd>
                <dt> @Html.DisplayNameFor(model => model.Description): </dt>
                <dd> @Html.DisplayFor(model => model.Description) </dd>
                <dt> @Html.DisplayNameFor(model => model.Location): </dt>
                <dd> @Html.DisplayFor(model => model.Location) </dd>
                <dt> @Html.DisplayNameFor(model => model.Opened): </dt>
                <dd> @Html.DisplayFor(model => model.Opened): </dd>
                <dt> @Html.DisplayNameFor(model => model.Closed) </dt>
                <dd> @Html.DisplayFor(model => model.Closed): </dd>
            </dl>
        </div>

        <div class="col-md-4">
            <dl class="dl-horizontal">
                <dt> @Html.DisplayNameFor(model => model.TaskNumber): </dt>
                <dd> @Html.DisplayFor(model => model.TaskNumber) </dd>
                <dt> @Html.DisplayNameFor(model => model.RCMPNumber): </dt>
                <dd> @Html.DisplayFor(model => model.RCMPNumber) </dd>
                <dt> @Html.DisplayNameFor(model => model.BCASNumber): </dt>
                <dd> @Html.DisplayFor(model => model.BCASNumber) </dd>
                <dt> @Html.DisplayNameFor(model => model.ASENumber): </dt>
                <dd> @Html.DisplayFor(model => model.ASENumber) </dd>
            </dl>
        </div>

        <div class="col-md-4">
            <img src=@Url.Action("show", "Incidents", new { id = Model.IncidentID }) />
        </div>

    </div>
    <dl class="dl-horizontal">
        <dt> @Html.DisplayNameFor(model => model.Agency.Name): </dt>
        <dd> @Html.DisplayFor(model => model.Agency.Name) </dd>
    </dl>
    @Html.DisplayFor(model => model.Core)
</div>