BlueDiamond/Controllers/AgencyController.cs
using System;
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using BlueDiamond.DataModel;
using BlueDiamond.Models;
using BlueDiamond.StorageModel;

namespace BlueDiamond.Controllers
{
    public class AgencyController : BaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public async Task<ActionResult> Index()
        {
            return View(await db.Agencies.ToListAsync());
        }

        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Agency agencyModel = await db.Agencies.FindAsync(id);
            if (agencyModel == null)
                return HttpNotFound();
            return View(agencyModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "AgencyID,Name,Description,TimeZone,TagString")] Agency agencyModel)
        {
            if (ModelState.IsValid)
            {
                agencyModel.AgencyID = Guid.NewGuid();
                agencyModel.Core = Core.Create(User.Identity.Name);
                db.Agencies.Add(agencyModel);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(agencyModel);
        }

        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Agency agencyModel = await db.Agencies.FindAsync(id);
            if (agencyModel == null)
                return HttpNotFound();
            return View(agencyModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "AgencyID,Name,Description,TimeZone,TagString")] Agency agencyModel)
        {
            if (ModelState.IsValid)
            {
                agencyModel.Core.Modify(User.Identity.Name);
                db.Entry(agencyModel).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(agencyModel);
        }

        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Agency agencyModel = await db.Agencies.FindAsync(id);
            if (agencyModel == null)
                return HttpNotFound();
            return View(agencyModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            Agency agencyModel = await db.Agencies.FindAsync(id);
            db.Agencies.Remove(agencyModel);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlueDiamond/Controllers/HomeController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using BlueDiamond.StorageModel;

namespace BlueDiamond.Controllers
{
    public class HomeController : BaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public async Task<ActionResult> Index()
        {
            var incidents = db
                .Incidents
                .Where(x => x.Closed == null)
                .Include(i => i.Agency)
                .OrderBy(x=>x.Opened);
            return View(await incidents.ToListAsync());
        }

        public ActionResult Time()
        { 
            return View();
        }

    }
}

BlueDiamond/Controllers/MembersController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CsvHelper;
using CsvHelper.Configuration;
using BlueDiamond.DataModel;
using BlueDiamond.StorageModel;

namespace BlueDiamond.Controllers
{
    public class MembersController : BaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Members
        public async Task<ActionResult> Index()
        {
            var members = db.Members.Include(m => m.Agency);
            return View(await members.ToListAsync());
        }

        // GET: Members/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member memberModel = await db.Members.FindAsync(id);
            if (memberModel == null)
            {
                return HttpNotFound();
            }
            return View(memberModel);
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            ViewBag.AgencyId = new SelectList(db.Agencies, "AgencyId", "Name");
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "MemberId,Core,FirstName,LastName,PhoneNumber,EmailAddress,AgencyID")] Member memberModel)
        {
            if (ModelState.IsValid)
            {
                memberModel.MemberID = Guid.NewGuid();
                db.Members.Add(memberModel);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.AgencyId = new SelectList(db.Agencies, "AgencyId", "Name", memberModel.AgencyID);
            return View(memberModel);
        }

        // GET: Members/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member memberModel = await db.Members.FindAsync(id);
            if (memberModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.AgencyId = new SelectList(db.Agencies, "AgencyId", "Name", memberModel.AgencyID);
            return View(memberModel);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "MemberId,Core,FirstName,LastName,PhoneNumber,EmailAddress,AgencyID")] Member memberModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(memberModel).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.AgencyId = new SelectList(db.Agencies, "AgencyId", "Name", memberModel.AgencyID);
            return View(memberModel);
        }

        // GET: Members/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member memberModel = await db.Members.FindAsync(id);
            if (memberModel == null)
            {
                return HttpNotFound();
            }
            return View(memberModel);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            Member memberModel = await db.Members.FindAsync(id);
            db.Members.Remove(memberModel);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public FileResult Export()
        {
            var members = db.Members.Include(m => m.Agency);
            MemoryStream ms = new MemoryStream();
            using (StreamWriter sw = new StreamWriter(ms))
            {
                using (var csv = new CsvWriter(sw))
                {
                    csv.Configuration.RegisterClassMap<MemberModelCSVMap>();
                    csv.WriteHeader(typeof(Member));
                    foreach (var member in members)
                        csv.WriteRecord(member);

                    sw.Flush();
                    byte[] bytes = ms.GetBuffer();
                    return File(bytes, "text/csv", "MemberNames.csv");
                }
                //ms.Position = 0;
            }
        }

        public sealed class MemberModelCSVMap : CsvClassMap<Member>
        {
            public MemberModelCSVMap()
            {
                Map(x => x.MemberID);
                Map(x => x.FirstName);
                Map(x => x.LastName);
                Map(x => x.PhoneNumber);
                Map(x => x.EmailAddress);
                Map(x => x.RoleID);
                Map(x => x.AgencyID);
            }

        }

        public ActionResult Import()
        {
            ViewBag.AgencyId = new SelectList(db.Agencies, "AgencyId", "Name");
            return View();
        }

        void UpdateMember(Member model)
        {
            Member member = db.Members.Find(model.MemberID);
            if (member == null)
                return;
            member.Update(model);
            db.SaveChanges();
        }

        [HttpPost]
        public ActionResult Import(HttpPostedFileBase file)
        {
            if (file.ContentLength <=0)
            {
                ViewBag.Error = "Error: file upload failed";
                return View("Error");
            }

            //var fileName = Path.GetFileName(file.FileName);
            //var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName);
            //file.SaveAs(path);

            using (var sw = new StreamReader(file.InputStream))
            {
                var csv = new CsvReader(sw);
                csv.Configuration.RegisterClassMap<MemberModelCSVMap>();
                csv.Configuration.IgnoreReadingExceptions = true;

                foreach (var model in csv.GetRecords<Member>())
                {
                    if (model.AgencyID == Guid.Empty)
                        model.AgencyID = null;
                    if (model.RoleID == Guid.Empty)
                        model.RoleID = null;

                    if (model.MemberID == Guid.Empty)
                    {
                        var member = db.Members.FirstOrDefault(x => x.FirstName == model.FirstName && x.LastName == model.LastName);
                        if (member == null)
                        {
                            model.MemberID = Guid.NewGuid();
                            db.Members.Add(model);
                        }
                        else
                            member.Update(model);
                        db.SaveChanges();

                    }
                    else
                    {
                        // update the model
                        if (db.Members.Find(model.MemberID) != null)
                            UpdateMember(model);
                        else
                            db.Members.Add(model);
                    }
                }

            }


            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlueDiamond/Views/Home/Index.cshtml
@model IEnumerable<BlueDiamond.DataModel.Incident>
@{
    ViewBag.Title = "BlueDiamond";
}

<div class="jumbotron">
    <div class="row">
        <div class="col-md-3">
            <img src="~/Content/Images/ICP300.png" width="200" height="200" />
        </div>
        <div class="col-md-9">
            <h1>Blue Diamond</h1>
            <p class="lead">Simple Incident Management.</p>
        </div>
    </div>
    @if (Model.Count() > 0)
    {
        <h2>Incidents</h2>

        <table class="table">
            <tr>
                <th> @Html.DisplayNameFor(model => model.TaskNumber) </th>
                <th> @Html.DisplayNameFor(model => model.Name) </th>
                <th> @Html.DisplayNameFor(model => model.Opened) </th>
                <th> @Html.DisplayNameFor(model => model.Closed) </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td> @Html.ActionLink(item.TaskNumber.ToString(), "Details", "Incidents", new { id = item.IncidentID }, new object { })
                    @*@Html.DisplayFor(modelItem => item.TaskNumber)*@ 
                    </td>
                    <td> @Html.DisplayFor(modelItem => item.Name) </td>
                    <td> @Html.DisplayFor(modelItem => item.Opened) </td>
                    <td> @Html.DisplayFor(modelItem => item.Closed) </td>
                    @*<td>
                        @Html.ActionLink("Edit", "Edit", "Incidents", new { id = item.IncidentID },new object{}) |
                        @Html.ActionLink("Details", "Details", "Incidents", new { id = item.IncidentID }, new object { }) |
                        @Html.ActionLink("Delete", "Delete", "Incidents", new { id = item.IncidentID }, new object { }) |
                        @Html.ActionLink("Sign In", "SignIn", "Incidents", new { id = item.IncidentID }, new object { })
                    </td>*@
                </tr>
            }

        </table>
    }
    else
    {
        <p>@Html.ActionLink("Create an incident", "Create", "Incidents", new object { }, new { @class = "btn btn-default" }) </p>
    }
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Incidents</h2>
        <p></p>
        <p>@Html.ActionLink("All Incidents", "Index", "Incidents", new object { }, new { @class = "btn btn-default" }) </p>
    </div>
    <div class="col-md-4">
        <h2>Members</h2>
        <p> </p>
        <p>@Html.ActionLink("List Members", "Index", "Members", new object { }, new { @class = "btn btn-default" }) </p>
    </div>
    <div class="col-md-4">
        <h2>Agencies</h2>
        <p> </p>
        <p>@Html.ActionLink("Agencies", "Index", "Agency", new object { }, new { @class = "btn btn-default" }) </p>
    </div>
</div>

BlueDiamond/Views/Home/Time.cshtml
@{
    ViewBag.Title = "Time";
}


<div class="row">
    <div class="col-md-6">
        <h3>Date</h3>
        <h2>
            <span id="largeDate"></span>
        </h2>
    </div>
    <div class="col-md-6">
        <h3>Time</h3>
        <h2>
            <span id="largeTime"></span>
        </h2>
    </div>
</div>
<hr/>

<div class="row">
    <div class="col-md-6">
        <h3>Location</h3>
        <h2>
            <span id="latitude"></span> <span id="longitude"></span> &plusmn; <span id="accuracy"></span>
        </h2>
    </div>
    <div class="col-md-6">
        <h3>UTM</h3>
        <h2>
            <span id="UTM"></span>
        </h2>
    </div>
</div>
<hr />

<div class="row">
    <div class="col-md-6">
        <h3>Sunrise</h3>
        <h2>
            <span id="sunrise"></span>
        </h2>
    </div>
    <div class="col-md-6">
        <h3>Sunset</h3>
        <h2>
            <span id="sunset"></span>
        </h2>
    </div>
</div>

<div class="well">
    <div id="StatusMessage"></div>
    <div id="Message"></div>
</div>

@using (Html.BeginScriptContext())
{
    Html.AddScriptFile("/Scripts/suncalc.js");
    Html.AddScriptFile("/Scripts/geog.js");
    Html.AddScriptBlock(

        @<script type="text/javascript">
            // using https://github.com/mourner/suncalc

            $(document).ready(function () {
                clock2();
                var clockInterval = setInterval(clock2, 1000);

                GeoLocate(
                        function (position) {
                            $("#latitude").text(position.latitude.toFixed(5));
                            $("#longitude").text(position.longitude.toFixed(5));
                            $("#accuracy").text(position.accuracy);

                            ConvertToUTM(
                                position.latitude,
                                position.longitude,
                                function (zone, easting, northing) {
                                    $("#UTM").text(zone + " " + easting + " " + northing);
                                });

                            // get today's sunlight times for London
                            var times = SunCalc.getTimes(new Date(), position.latitude, position.longitude);

                            $("#sunrise").text(times.sunrise.toLocaleTimeString());
                            $("#sunset").text(times.sunset.toLocaleTimeString());

                            $("#StatusMessage").text("Location found on " + new Date());

                        },
                        function (error) {
                            $("#StatusMessage").text(msg);
                            $("#Message").val("The subject loaded the web page on\n"
                                + "     " + new Date() + "\n"
                                + "and their location <b>could not be determined</b><br/>\n"
                                + "The message was:\n"
                                + "\"" + err.message + "\""
                            );
                        }
                    );
            });

            function clock2() {
                var s = (new Date()).toLocaleTimeString();
                var d = (new Date()).toDateString();
                $('#largeDate').text(s);
                $('#largeTime').text(d);
                //document.getElementById('time').innerHTML = s;
            }


        </script>
    );
}